# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
    - id: Fmt
      name: fmt
      entry: cargo fmt
      language: system
      types: [rust]
      args: ["--"]
      pass_filenames: false

    - id: Sqlx Prepare
      name: Sqlx Prepare
      entry: cargo sqlx prepare
      language: system
      types: [rust]
      pass_filenames: false

    - id: Sqlx Prepare Add files
      name: Sqlx Prepare Add files
      entry: git add ./.sqlx
      language: system
      pass_filenames: false

    - id: Clippy
      name: clippy
      entry: cargo hack clippy --feature-powerset -- -D warnings
      language: system
      types: [rust]
      pass_filenames: false