name: Rust

on:
  push:
    branches: [ "master", "main", "develop"]
  pull_request:
    branches: [ "master", "main", "develop" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

jobs:
  dependancies:
    env: 
      SQLX_OFFLINE: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-machete
      run: cargo install cargo-machete --locked
    - name: Run cargo-machete
      run: cargo machete