name: Rust
permissions:
  contents: read

on:
  push:
    branches: [ "master", "main", "develop"]
  pull_request:
    branches: [ "master", "main", "develop" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

jobs:
  semver_checks:
    env: 
      SQLX_OFFLINE: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: Swatinem/rust-cache@v2
    - name: Install cargo-semver-checks
      run: cargo install cargo-semver-checks --locked
    - name: Run cargo-semver-checks
      run: cargo semver-checks --all-features